### ISSUE TITLE
Images with the same tags multiple times

### ISSUE THREAD

**Issue by davenquinn** [UW-COSMOS/cosmos-visualizer#6]
@cambro has found some double tagged images (same tags twice) on the validation side of the API. Thinking about how the frontend code works, it’s likely because, during the first annotation session on the frontend, new tags are not assigned a UUID yet, so they can be repeatedly saved with new UUIDs on the backend.

We could solve this two ways:

1. Generate tag UUIDs on the frontend on initial creation. That way a tag persisted to the database   multiple times would just overwrite previous values of the tag
2. Have the `/images/…/tags [POST]` route return the entire collection of tags as a response (same signature as `/images/…/tags [GET]`). That way the frontend could replace the tag collection with the UUID-containing values from the backend

It seems that option 1 is a bit more flexible, the backend would just have to use the frontend-supplied UUID if set. In both options, the backend would have to deconflict changes by replacing UUID-owning tags with their updated values.

Another option that may obviate the need for all of this would be to do some post-processing of the tag store to only accept the most recent tagging session...or to only return tags from one session at a time for validation

**Comment by davenquinn** [comment]
This whole tagging/validation split is a tricky workflow to support

**Comment by davenquinn** [comment]
Mostly solved by af0dc3a4fd6907a0ba98c95f46cd4d98a9bf7050, will leave this open for the moment.

**Comment by jczaplew** [comment]
@davenquinn can you confirm that af0dc3a resolved this issue?

**Comment by davenquinn** [comment]
Yep all fixed!

**Comment by jczaplew** [comment]
Great! Thanks!

**Comment by cambro** [comment]
This is not fixed. Saving 2x for the same image during annotation, for example if you make a mistake, catch it, and correct it, will result in duplicated tags.

**Comment by davenquinn** [comment]
This is why we sync the uids between the backend and frontend, right? So I guess it is fixed on the frontend but not fully on the backend.
